name: ci-dev-oidc

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/ci-dev-oidc.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/ci-dev-oidc.yml'

permissions:
  id-token: write     # required for GitHub OIDC -> AWS
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Run every shell step from the infra/ folder
    defaults:
      run:
        working-directory: infra

    env:
      AWS_REGION: us-east-2
      AWS_ROLE_ARN: arn:aws:iam::382773571217:role/HUNTECH-GitHubOIDC-Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -upgrade -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format (check)
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan -input=false -no-color
