name: Terraform CI (fmt check + init + validate + auto-fix PR)

on:
  pull_request:
    paths: ["**/*.tf", "**/*.tfvars"]
  push:
    branches: [ main ]
    paths: ["**/*.tf", "**/*.tfvars"]
  workflow_dispatch:

jobs:
  tf_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    env:
      TF_IN_AUTOMATION: "true"
      AWS_REGION: us-east-1
      ROLE_TO_ASSUME: arn:aws:iam::382773571217:role/HUNTECH-CICD
      MODULE_PATH: infra

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }

      - name: fmt check
        id: fmt
        working-directory: ${{ env.MODULE_PATH }}
        continue-on-error: true
        run: terraform fmt -recursive -check

      - name: Auto-fix fmt and open PR (if failed)
        if: steps.fmt.outcome == 'failure'
        run: |
          set -e
          cd "${MODULE_PATH}"
          terraform fmt -recursive
          cd -
          git config user.name  "huntech-ci"
          git config user.email "huntech-ci@users.noreply.github.com"
          git checkout -b chore/tf-fmt-${{ github.run_id }}
          git add -A
          git commit -m "chore(tf): auto-format via CI"
          git push --set-upstream origin chore/tf-fmt-${{ github.run_id }}

      - name: Create PR for fmt (if branch exists)
        if: steps.fmt.outcome == 'failure'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/tf-fmt-${{ github.run_id }}
          title: "chore(tf): auto-format via CI"
          body: "This PR was created automatically by Terraform CI."
          base: main
          labels: chore, terraform

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform init
        working-directory: ${{ env.MODULE_PATH }}
        run: terraform init -input=false -upgrade

      - name: terraform validate
        working-directory: ${{ env.MODULE_PATH }}
        run: terraform validate
