name: Terraform Validate

on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "Path to the Terraform module (folder that has main.tf)"
        required: false
        default: "."
  push:
    branches: [ main ]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Resolve module path
        id: mp
        shell: bash
        run: |
          MP="${{ github.event.inputs.module_path }}"
          if [ -z "$MP" ]; then MP="."; fi
          echo "MODULE_PATH=$MP" >> $GITHUB_ENV
          echo "Module path: $MP"
      - name: terraform fmt (check)
        working-directory: ${{ env.MODULE_PATH }}
        run: terraform fmt -recursive -check
      - name: terraform init
        working-directory: ${{ env.MODULE_PATH }}
        run: terraform init -input=false -upgrade
      - name: terraform validate
        working-directory: ${{ env.MODULE_PATH }}
        run: terraform validate
